### ISSUE TITLE
Efficiency of redundant fuzzers

### ISSUE THREAD

**Issue by mutantzombie** [yahoo/gryffin#15]
Both sqlmap and arachni have SQL injection capabilities. Why run both? It doesn't look like there's an attempt to pare down either to a specific configuration or avoid running identical payloads.

**Comment by Zapotek** [comment]
Arachni's capabilities are actually a superset of sqlmap's under this context[1] so it should suffice.
Although if you follow that train of thought to the end you'd end up at "Just setup Arachni as a [Grid](https://github.com/Arachni/arachni/wiki/RPC-server#setup-grid) and skip Gryffin altogether" so you've got to draw the line somewhere.

In any case, in its current setup Gryffin uses sqlmap for SQL injection and Arachni for [XSS](https://github.com/yahoo/gryffin/blob/master/fuzzer/arachni/arachni.go#L26) so there won't be any overlap.

[1] Arachni doesn't have exploitation features but Gryffin is scan only anyways.

**Comment by yukinying** [comment]
Is Arachni's SQLi vector taken from SQLMap? I tried to follow the sql injection related changes on Arachni and was lost. I can find related commits in non-master branch, and it is no longer in master: https://github.com/Arachni/arachni/blob/master/external/metasploit/modules/exploits/unix/webapp/arachni_sqlmap.rb

**Comment by Zapotek** [comment]
That was an old Metasploit module for SQL injections that delegated to sqlmap -- if I remember correctly.
SQL injections in Arachni are handled by the following [checks](https://github.com/Arachni/arachni/tree/experimental/components/checks/active):
- `sql_injection` -- Error based.
- `sql_injection_differential` -- Blind, performing differential analysis on boolean injections.
- `sql_injection_timing` -- Blind, performing timing attacks.

**Comment by yukinying** [comment]
I see. It would be interesting for us to make Arachni SQLi detection available as a separate plugin and run some back-by-back testing against SQLmap. 

Since both Arachni and SQLMap are both active projects, I admit that I am not up-to-date to comment which one is a superset of the other or not. Also this github project would not be a proper place for such discussion. Should that discussion be happening in the Arachni or SQLMap project page?

**Comment by Zapotek** [comment]
By superset I meant that Arachni covers the vulnerability identification features of SQLmap (i.e. SQL injections) as well many other features, while SQLmap is SQL injection only.

I don't see why this discussion would be happening anywhere else though since the issue @mutantzombie raised is whether or not it makes sense to have dependencies with redundant features, and that only applies to Gryffin.

In any case, I'm just giving you the lowdown on Arachni, I can't speak of much else with any sort of authority.

**Comment by mutantzombie** [comment]
I'd summarize sqlmap as an exploit tool and arachni as a distributed vuln scanner. Sqlmap addresses the use cases around pen testing (extract info from the DB, execute commands). Arachni addresses vulnerability scanning (crawl and discover resources, identify vulns in those resources). It'd be reasonable to say arachni is a superset in terms of scanning features.

In addition to test vectors, a scanner needs to have strong heuristics around applying those payloads and minimizing false positives. Both tools score well on wavsep (as one reference). Their differences are really in purpose.

Sqlmap provides many command line options for tuning, but these don't seem to be leveraged beyond a specific default. Arachni can run SQL injection tests alongside XSS (and others). I would imagine consolidating tests could improve efficiency in terms of how a fuzzer performs internally, as well as things like "cold start" mentioned in #9.

I was curious what motivated this choice.

**Comment by r-andrew-dev** [comment]
The project is being archived.
